#resnet50
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet50/resnet50_csv_90.h5 csv /home/huray/data/new_trainset/0919_new_train_data_only_abnormal_exclude_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet50/resnet50_csv_84.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet50/resnet50_csv_90.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#resnet101
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet101/resnet101_csv_59.h5 csv /home/huray/data/new_trainset/0919_new_train_data_only_abnormal_exclude_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet101/resnet101_csv_61.h5 csv /home/huray/data/new_trainset/0919_new_train_data_only_abnormal_exclude_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet101/resnet101_csv_59.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet101/resnet101_csv_61.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#resnet152
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet152/resnet152_csv_44.h5 csv /home/huray/data/new_trainset/0919_new_train_data_only_abnormal_exclude_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet152/resnet152_csv_74.h5 csv /home/huray/data/new_trainset/0919_new_train_data_only_abnormal_exclude_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet152/resnet152_csv_44.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &
#nohup python -u keras_retinanet/bin/new_train.py --snapshot snapshots/resnet152/resnet152_csv_74.h5 csv /home/huray/data/new_trainset/1211_new_train_data_only_abnormal_include_NCC_test.csv /home/huray/data/new_trainset/class_2_malig_or_norm.csv  --evaluation True --val-annotations /home/huray/data/new_trainset/0919_new_valid_data_NCC_test_only_anno.csv &

